version: 2.1

workflows:
  build:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/node:16.13.2
    steps:
      - checkout
      - run:
          name: Set up Node.js
          command: |
            echo "##[group] Installing Node.js"
            curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
            echo "##[endgroup]"
      - run: npm ci
      - run: npm test
    post_steps:
      - coveralls/upload
