version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm test
      - persist_to_workspace:
          root: .
          paths:
            - .env  # Persist .env file for later use

  deploy:
    docker:
      - image: circleci/node:14
    working_directory: /home/circleci/project  # Ensure this is correct
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Deploy to Server
          command: npm run deploy
          
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

deploy:
  docker:
    - image: circleci/node:14
  working_directory: /home/circleci/project
  steps:
    - attach_workspace:
        at: .
    - run:
        name: List Files in Workspace
        command: ls -al
    - run:
        name: Install Dependencies
        command: npm install
    - run:
        name: Deploy to Server
        command: npm run deploy
