version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14.17.6
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: |
            # Use the predefined CircleCI environment variable for MongoDB URI
            echo "Running tests with MongoDB URI: $MONGODB_URI"
            npm test
      - store_test_results:
          path: test-results

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
